import Foundation
import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case de, en, fr, es, it, nl, ja, zhHans
    var id: String { rawValue }

    var label: String {
        switch self {
        case .de: return "Deutsch"
        case .en: return "English"
        case .fr: return "Français"
        case .es: return "Español"
        case .it: return "Italiano"
        case .nl: return "Nederlands"
        case .ja: return "日本語"
        case .zhHans: return "简体中文"
        }
    }

    var symbol: String {
        switch self {
        case .de: return "🇩🇪"
        case .en: return "🇬🇧"
        case .fr: return "🇫🇷"
        case .es: return "🇪🇸"
        case .it: return "🇮🇹"
        case .nl: return "🇳🇱"
        case .ja: return "🇯🇵"
        case .zhHans: return "🇨🇳"
        }
    }
}

@MainActor
final class Localizer: ObservableObject {
    static let shared = Localizer()

    @Published var language: AppLanguage {
        didSet {
            UserDefaults.standard.set(language.rawValue, forKey: "BUS.language")
        }
    }
    @Published var hasCompletedLanguageSelection: Bool {
        didSet { UserDefaults.standard.set(hasCompletedLanguageSelection, forKey: "BUS.languageSelected") }
    }

    private init() {
        let saved = UserDefaults.standard.string(forKey: "BUS.language")
        language = AppLanguage(rawValue: saved ?? "") ?? .de
        hasCompletedLanguageSelection = UserDefaults.standard.bool(forKey: "BUS.languageSelected")
    }

    func t(_ key: String) -> String {
        Self.strings[language]?[key] ?? Self.strings[.en]?[key] ?? key
    }

    private static let strings: [AppLanguage: [String: String]] = [
        .de: [
            "learningProgress":"Lernfortschritt","learningProgressInfo":"BUS verbessert die Schätzungen mit jeder Messung.","learningCharging":"Laden","learningAppUsage":"App-Nutzung","learningConsumption":"Verbrauchsdaten","learningRuntime":"Laufzeit-Referenzen","learningCollecting":"wird gesammelt","learningStateCollecting":"Sammelphase","learningStatePreliminary":"Vorläufig","learningStateStable":"Stabil","noQualifiedSessions":"keine gültige Sitzung","samples":"Proben","available":"verfügbar",
            "overview":"Übersicht","overviewSubtitle":"Alle wichtigen Informationen auf einen Blick.","history":"Verlauf","consumers":"Verbraucher","personalProfile":"Dein Profil","personalProfileSubtitle":"Deine persönliche Systemnutzung der letzten 30 Tage.","personalProfileApps":"App-Nutzung","personalProfileAppsInfo":"Energieverbrauch und Nutzungsdauer nach App, inklusive Hintergrundprozessen.","personalProfileNoData":"Noch keine 30-Tage-Daten vorhanden.","unknownApp":"Unbekannte App","groupedProcessesInfo":"Zugehörige Hilfs-, Renderer- und Hintergrundprozesse werden pro App zusammengefasst.","process":"Prozess","processes":"Prozesse","settings":"Einstellungen","about":"Über BUS",
            "battery":"Akku","power":"Leistung","energy":"Energie","foreground":"Vordergrund","background":"Hintergrund","duration":"Dauer","status":"Status","batteryMode":"Akkubetrieb","mainsMode":"Netzbetrieb",
            "score":"BUS Score","excellent":"Ausgezeichnet","veryGood":"Sehr gut","good":"Gut","elevated":"Erhöhter Verbrauch","high":"Hoher Verbrauch",
            "batteryHistory":"Akkuverlauf","lastHours":"Aktuelle Messsitzung","topConsumers":"Top-Verbraucher","noData":"Noch keine auswertbaren Messdaten",
            "openOverview":"Übersicht öffnen","pause":"Pause","start":"Start","quit":"BUS beenden","reset":"Zurücksetzen","export":"Export",
            "app":"App","share":"Anteil","estimatedBattery":"Akku geschätzt","cpu":"CPU","disk":"I/O","wakeups":"Wakeups",
            "groupByApp":"Nach App",
            "groupByProcess":"Nach Prozess",
            "showAll":"Alle anzeigen",
            "showActive":"Nur aktiv",
            "showSignificant":"Ab 1 %",
            "appProcess":"App / Prozess",
            "total":"Gesamtsumme",
            "mainProcess":"Hauptprozess",
            "historicalProcess":"Frühere Messung",
            "general":"Allgemein","startAtLogin":"Beim Anmelden automatisch starten","measurement":"Messung","interval":"Messintervall",
            "startHiddenAtLogin":"Beim Start nur in der Menüleiste öffnen",
            "startHiddenAtLoginHelp":"Wenn BUS automatisch startet, bleibt nur die Menüleisten-Ansicht geöffnet.",
            "menuBar":"Menüleiste",
            "menuBarBatteryDisplay":"Akkusymbol",
            "menuBarIconOnly":"Nur Symbol",
            "menuBarIconWithPercent":"Prozent im Symbol",
            "menuBarColorizeBattery":"Symbol einfärben",
            "menuBarShowRemainingTime":"Restlaufzeit anzeigen",
            "menuBarRemainingTimeHelp":"Im Akkubetrieb zeigt BUS die geschätzte Restlaufzeit, beim Laden die geschätzte Ladezeit bis 100 %.",
            "lowPowerMode":"Energiesparmodus",
            "lowPowerMode.off":"Aus",
            "lowPowerMode.on":"Ein",
            "lowPowerMode.automatic":"Automatisch",
            "lowPowerModeThreshold":"Automatisch ab",
            "lowPowerModeStatus":"Status",
            "lowPowerModeSystemActive":"macOS aktiv",
            "lowPowerModeOffStatus":"Aus",
            "lowPowerModeOnStatus":"macOS wird aktiviert",
            "lowPowerModeAutomaticActive":"Automatisch aktiv",
            "lowPowerModeAutomaticWaiting":"Wartet auf Schwelle",
            "lowPowerModeHelp":"BUS steuert die echte macOS-Funktion „Leistung reduzieren“ über den installierten Hardware Helper. Die Administratorfreigabe erfolgt bei der Installation/Aktualisierung des Helpers; danach kann BUS den Zustand ohne weitere Passwortabfrage schalten. Der Status wird direkt aus der macOS-Energieverwaltung gelesen.",
            "debugging":"Debugging",
            "debugLogging":"Debug-Log auf dem Schreibtisch schreiben",
            "debugLoggingHelp":"Wenn aktiviert, schreibt BUS Start- und Fensterdiagnosen nach ~/Desktop/BUS-Debug.log.",
            "autoReset":"Messzyklus nach dem Laden automatisch zurücksetzen","autoResetAtFull":"Erst bei 100 % zurücksetzen","language":"Sprache","privacy":"Datenschutz",
            "privacyTitle":"100 % lokal","privacyText":"BUS überträgt keine Messwerte, Nutzungsdaten oder Telemetrie. Die App enthält keinen Netzwerkzugriff und funktioniert vollständig offline.",
            "deleteData":"Alle lokalen Messdaten löschen","confirmDelete":"Lokale Messdaten wirklich löschen?","cancel":"Abbrechen","delete":"Löschen",
            "welcome":"Willkommen bei BUS","chooseLanguage":"Wähle deine Sprache","continue":"Weiter","offlineBadge":"Keine Datenübertragung",
            "credit":"BUS – Battery Usage Score von Heiko Große & ChatGPT © 2026","version":"Version",
            "estimateInfo":"Die App-Anteile sind nachvollziehbare Schätzungen aus Akkuentladung, CPU-Zeit, Datenträger-I/O und Wakeups.",
            "charging":"Lädt","remaining":"Akkustand","updated":"Aktualisiert","scoreExplanation":"Je höher der BUS Score, desto effizienter arbeitet dein Mac im Batteriebetrieb.",
            "scoreDetails":"Score-Aufschlüsselung",
            "currentProjection":"Aktuelle Gesamtlaufzeit",
            "manufacturerReference":"Hersteller-Referenz",
            "personalMedian":"Persönlicher Median",
            "modelScore":"Modell-Effizienz",
            "personalScore":"Persönliche Effizienz",
            "personalRuntime":"Persönliche Akkulaufzeit",
            "remainingEstimate":"Geschätzte Restlaufzeit",
            "thirtyDayAverage":"30-Tage-Durchschnitt",
            "qualifiedSessions":"Gewertete Sitzungen",
            "runtimeStatisticsInfo":"Nur Batteriesitzungen ab 10 Minuten und mindestens 3 % Entladung fließen in die Statistik ein.",
            "batterySessions":"Lokale Batteriesitzungen",
            "noRuntimeSessions":"Noch keine ausreichend lange Batteriesitzung gespeichert.",
            "deviceReference":"Geräte-Referenz",
            "detectedModel":"Erkanntes Modell",
            "automaticReference":"Automatische Referenz",
            "manualReference":"Manuelle Referenz",
            "automatic":"Automatisch",
            "notAvailable":"Nicht hinterlegt",
            "referenceInfo":"BUS verwendet die lokale Modellreferenz. Bei unbekannten Modellen kann die Herstellerlaufzeit manuell hinterlegt werden.",
            "profileReferenceLearned":"Aus %d Sitzungen gelernt · %2$@",
            "profileReferenceFallback":"Lernphase: integrierte Modell- und Profilreferenz wird verwendet, bis mindestens drei Sitzungen vorliegen.",
            "comparisonProfile":"Vergleichsprofil",
            "currentProfileTime":"Zeit im aktuellen Profil",
            "automaticLookback":"Persönlicher Vergleichszeitraum",
            "automaticLookbackHelp":"Automatisch gewichtet die Nutzung der letzten %d Tage. Die Profilreferenzen werden aus bis zu 30 Tagen gelernt; bis drei Sitzungen vorliegen, bleibt die integrierte Vergleichsreferenz aktiv.",
            "days":"Tage",
            "predictionData":"Persönliche Vorhersage",
            "predictionStatus":"Vorhersagestatus",
            "predictionConfidenceLearning":"Lernphase",
            "predictionConfidenceMedium":"zunehmend belastbar",
            "predictionConfidenceHigh":"sehr belastbar",
            "predictionDataHelp":"BUS berechnet minutengenaue Werte aus vergleichbaren lokalen Batteriesitzungen und Ladekurven. Aktuelle Daten sind aussagekräftiger als alte Daten.",
            "predictionSubtitle":"Minutengenaue lokale Prognose aus vergleichbaren Batteriesitzungen der letzten %d Tage.",
            "comparisonAverage":"Durchschnitt der letzten %d Tage",
            "chargeLearningData":"Ladekurven-Messfenster",
            "appActivityLearningData":"App-Zustandsmessungen",
            "deletePredictionData":"Persönliche Vorhersagedaten löschen",
            "confirmDeletePredictionData":"Persönliche Laufzeit- und Ladedaten wirklich löschen?",
            "scorePaused":"Pausiert",
            "scorePausedExplanation":"Der BUS Score wird im Netzbetrieb nicht bewertet.",
            "scoreCollecting":"Wird ermittelt",
            "scoreCollectingExplanation":"BUS sammelt mindestens drei Minuten Messdaten, bevor der Score bewertet wird.",
            "scoreReferenceMissing":"Referenz fehlt",
            "scoreReferenceMissingExplanation":"Für dieses Modell ist noch keine Hersteller- oder persönliche Referenz vorhanden.",
            "scoreRuntimeComparison":"Aktuell %.1f Stunden gegenüber %.1f Stunden Referenz.",
            "searchApps":"Apps und Prozesse suchen",
            "sortByColumn":"Nach dieser Spalte sortieren",
            "chargingActive":"Akku wird geladen",
            "fullyCharged":"Vollständig geladen",
            "chargeHolding":"Ladestand wird gehalten",
            "adapterPower":"Netzteil-Leistung",
            "systemConsumption":"Systemverbrauch",
            "batteryChargingPower":"Akku-Ladeleistung",
            "timeTo80":"Restzeit bis 80 %",
            "timeToFull":"Restzeit bis 100 %",
            "runtimeCurrentCharge":"Laufzeit mit aktuellem Ladestand",
            "runtimeFullCharge":"Laufzeit bei voller Ladung",
            "chargeSpeed":"Ladegeschwindigkeit",
            "chargeLearning":"Lokale Ladekurve",
            "chargeLearningWindows":"%d Messfenster",
            "chargeLearningCollecting":"wird gelernt",
            "chargeLearningMedium":"mittlere Sicherheit",
            "chargeLearningHigh":"hohe Sicherheit",
            "chargingEstimateInfo":"Ladezeiten und Leistungsflüsse sind lokale, geglättete Schätzwerte. Oberhalb von 80 % berücksichtigt BUS die reduzierte Ladeleistung.",
            "estimated":"Geschätzt",
            "calculating":"Wird ermittelt …",
            "reached":"Erreicht",
            "profiles":"Profile",
            "profilesSubtitle":"Wähle ein Nutzungsprofil oder lasse BUS die aktuelle Nutzung automatisch erkennen.",
            "usageProfile":"Nutzungsprofil",
            "activeProfile":"Aktives Profil",
            "detectedProfile":"Automatisch erkannt",
            "automaticallyDetected":"Automatisch erkannt",
            "manuallySelected":"Manuell ausgewählt",
            "expectedRuntime":"Erwartete Laufzeit",
            "profileEfficiency":"Profil-Effizienz",
            "profileReference":"Profil-Referenz",
            "powerBalance":"Leistungsbilanz",
            "powerBalanceSubtitle":"Entnahme positiv · Energiezufuhr negativ",
            "energyDraw":"Energieentnahme",
            "energyInput":"Energiezufuhr",
            "profile.automatic.title":"Automatisch",
            "profile.automatic.description":"BUS erkennt die aktuelle Nutzung und mischt sie mit deinen gelernten Profilzeiten. In der Lernphase dient die integrierte Modellreferenz als Vergleich.",
            "profile.office.title":"Office",
            "profile.office.description":"E-Mail, Dokumente, Tabellen, Präsentationen und Kommunikation.",
            "profile.browser.title":"Browser",
            "profile.browser.description":"Web, Kommunikation, Streaming und browserbasierte Anwendungen.",
            "profile.developer.title":"Developer",
            "profile.developer.description":"Xcode, IDEs, Terminal, Docker, Compiler und Simulatoren.",
            "profile.creative.title":"Creative",
            "profile.creative.description":"Bildbearbeitung, Design, Fotografie und 3D-Anwendungen.",
            "profile.video.title":"Video",
            "profile.video.description":"Videoschnitt, Rendering, Encoding und Medienproduktion.",
            "profile.gaming.title":"Gaming",
            "profile.gaming.description":"Spiele, 3D-Grafik und dauerhaft hohe CPU-/GPU-Last.",
            "profile.audio.title":"Audio",
            "profile.audio.description":"Musikproduktion, DAWs, Plugins und Audioverarbeitung.",
            "profile.mixed.title":"Gemischt",
            "profile.mixed.description":"Ausgewogene Nutzung aus mehreren unterschiedlichen Bereichen.",
            "currentInputPower":"Aktuelle Eingangsleistung",
            "adapterMaximum":"Netzteil max.",
            "hardwareMeasured":"Per Hardware-Sensor gemessen",
            "hardwarePartiallyMeasured":"Akku gemessen · Eingang abgeleitet",
            "locallyEstimated":"Lokal geschätzt",
            "hardwareHelper":"BUS Hardware Helper",
            "helperInstalled":"Hardware Helper aktiv",
            "helperMissing":"Hardware Helper nicht verfügbar",

        ],
        .en: [
            "learningProgress":"Learning progress","learningProgressInfo":"BUS improves its estimates with every measurement.","learningCharging":"Charging","learningAppUsage":"App usage","learningConsumption":"Consumption data","learningRuntime":"Runtime references","learningCollecting":"collecting","learningStateCollecting":"Collecting","learningStatePreliminary":"Preliminary","learningStateStable":"Stable","noQualifiedSessions":"no qualified session","samples":"samples","available":"available",
            "overview":"Overview","overviewSubtitle":"All important information at a glance.","history":"History","consumers":"Consumers","personalProfile":"Your Profile","personalProfileSubtitle":"Your personal system usage over the last 30 days.","personalProfileApps":"App usage","personalProfileAppsInfo":"Energy use and time spent by app, including background processes.","personalProfileNoData":"No 30-day data available yet.","unknownApp":"Unknown app","groupedProcessesInfo":"Related helper, renderer and background processes are grouped by app.","process":"process","processes":"processes","settings":"Settings","about":"About BUS",
            "battery":"Battery","power":"Power","energy":"Energy","foreground":"Foreground","background":"Background","duration":"Duration","status":"Status","batteryMode":"On battery","mainsMode":"Power adapter",
            "score":"BUS Score","excellent":"Excellent","veryGood":"Very good","good":"Good","elevated":"Elevated usage","high":"High usage",
            "batteryHistory":"Battery history","lastHours":"Current measurement session","topConsumers":"Top consumers","noData":"No evaluable data yet",
            "openOverview":"Open overview","pause":"Pause","start":"Start","quit":"Quit BUS","reset":"Reset","export":"Export",
            "app":"App","share":"Share","estimatedBattery":"Estimated battery","cpu":"CPU","disk":"I/O","wakeups":"Wakeups",
            "groupByApp":"By app",
            "groupByProcess":"By process",
            "showAll":"Show all",
            "showActive":"Active only",
            "showSignificant":"At least 1%",
            "appProcess":"App / process",
            "total":"Total",
            "mainProcess":"Main process",
            "historicalProcess":"Previous measurement",
            "general":"General","startAtLogin":"Launch at login","measurement":"Measurement","interval":"Sample interval",
            "startHiddenAtLogin":"Open in menu bar only at startup",
            "startHiddenAtLoginHelp":"When BUS launches automatically, only the menu bar view stays open.",
            "menuBar":"Menu bar",
            "menuBarBatteryDisplay":"Battery icon",
            "menuBarIconOnly":"Icon only",
            "menuBarIconWithPercent":"Percentage inside icon",
            "menuBarColorizeBattery":"Colorize icon",
            "menuBarShowRemainingTime":"Show remaining time",
            "menuBarRemainingTimeHelp":"On battery BUS shows the estimated remaining runtime; while charging it shows the estimated time to 100%.",
            "lowPowerMode":"Low Power Mode",
            "lowPowerMode.off":"Off",
            "lowPowerMode.on":"On",
            "lowPowerMode.automatic":"Automatic",
            "lowPowerModeThreshold":"Automatic at",
            "lowPowerModeStatus":"Status",
            "lowPowerModeSystemActive":"macOS active",
            "lowPowerModeOffStatus":"Off",
            "lowPowerModeOnStatus":"macOS is being enabled",
            "lowPowerModeAutomaticActive":"Automatic active",
            "lowPowerModeAutomaticWaiting":"Waiting for threshold",
            "lowPowerModeHelp":"BUS controls the real macOS Low Power Mode through the installed hardware helper. Administrator approval happens when the helper is installed or updated; after that BUS can switch the state without another password prompt. The status is read directly from macOS power management.",
            "debugging":"Debugging",
            "debugLogging":"Write debug log to Desktop",
            "debugLoggingHelp":"When enabled, BUS writes startup and window diagnostics to ~/Desktop/BUS-Debug.log.",
            "autoReset":"Reset measurement after charging automatically","autoResetAtFull":"Reset only at 100%","language":"Language","privacy":"Privacy",
            "privacyTitle":"100% local","privacyText":"BUS does not transmit measurements, usage data or telemetry. The app contains no network access and works fully offline.",
            "deleteData":"Delete all local measurement data","confirmDelete":"Really delete all local measurement data?","cancel":"Cancel","delete":"Delete",
            "welcome":"Welcome to BUS","chooseLanguage":"Choose your language","continue":"Continue","offlineBadge":"No data transmission",
            "credit":"BUS – Battery Usage Score by Heiko Große & ChatGPT © 2026","version":"Version",
            "estimateInfo":"Per-app shares are transparent estimates based on battery discharge, CPU time, disk I/O and wakeups.",
            "charging":"Charging","remaining":"Battery level","updated":"Updated","scoreExplanation":"The higher the BUS Score, the more efficiently your Mac runs on battery.",
            "scoreDetails":"Score breakdown",
            "currentProjection":"Current full runtime",
            "manufacturerReference":"Manufacturer reference",
            "personalMedian":"Personal median",
            "modelScore":"Model efficiency",
            "personalScore":"Personal efficiency",
            "personalRuntime":"Personal battery runtime",
            "remainingEstimate":"Estimated remaining time",
            "thirtyDayAverage":"30-day average",
            "qualifiedSessions":"Qualified sessions",
            "runtimeStatisticsInfo":"Only battery sessions lasting at least 10 minutes with at least 3% discharge are included.",
            "batterySessions":"Local battery sessions",
            "noRuntimeSessions":"No sufficiently long battery session has been stored yet.",
            "deviceReference":"Device reference",
            "detectedModel":"Detected model",
            "automaticReference":"Automatic reference",
            "manualReference":"Manual reference",
            "automatic":"Automatic",
            "notAvailable":"Not available",
            "referenceInfo":"BUS uses its local model reference. For unknown models, the manufacturer runtime can be entered manually.",
            "profileReferenceLearned":"Learned from %d sessions · %2$@",
            "profileReferenceFallback":"Learning phase: built-in model and profile reference is used until at least three sessions are available.",
            "comparisonProfile":"Comparison profile",
            "currentProfileTime":"Time in current profile",
            "automaticLookback":"Personal comparison period",
            "automaticLookbackHelp":"Automatic mode weights usage from the last %d days. Profile references learn from up to 30 days; until three sessions are available, the built-in comparison reference remains active.",
            "days":"days",
            "predictionData":"Personal prediction",
            "predictionStatus":"Prediction status",
            "predictionConfidenceLearning":"learning phase",
            "predictionConfidenceMedium":"becoming reliable",
            "predictionConfidenceHigh":"highly reliable",
            "predictionDataHelp":"BUS calculates minute-accurate values from comparable local battery sessions and charge curves. Current data is more meaningful than old data.",
            "predictionSubtitle":"Minute-accurate local forecast from comparable battery sessions in the last %d days.",
            "comparisonAverage":"Average from the last %d days",
            "chargeLearningData":"Charge-curve sample windows",
            "appActivityLearningData":"App state samples",
            "deletePredictionData":"Delete personal prediction data",
            "confirmDeletePredictionData":"Really delete personal runtime and charging data?",
            "scorePaused":"Paused",
            "scorePausedExplanation":"The BUS Score is not evaluated while connected to power.",
            "scoreCollecting":"Collecting",
            "scoreCollectingExplanation":"BUS collects at least three minutes of data before evaluating the score.",
            "scoreReferenceMissing":"Reference missing",
            "scoreReferenceMissingExplanation":"No manufacturer or personal reference is available for this model yet.",
            "scoreRuntimeComparison":"Currently %.1f hours compared with %.1f reference hours.",
            "searchApps":"Search apps and processes",
            "sortByColumn":"Sort by this column",
            "chargingActive":"Battery is charging",
            "fullyCharged":"Fully charged",
            "chargeHolding":"Charge level is being held",
            "adapterPower":"Adapter power",
            "systemConsumption":"System consumption",
            "batteryChargingPower":"Battery charging power",
            "timeTo80":"Time to 80%",
            "timeToFull":"Time to 100%",
            "runtimeCurrentCharge":"Runtime at current charge",
            "runtimeFullCharge":"Runtime at full charge",
            "chargeSpeed":"Charging speed",
            "chargeLearning":"Local charge curve",
            "chargeLearningWindows":"%d sample windows",
            "chargeLearningCollecting":"learning",
            "chargeLearningMedium":"medium confidence",
            "chargeLearningHigh":"high confidence",
            "chargingEstimateInfo":"Charging times and power flows are local, smoothed estimates. Above 80%, BUS accounts for charging taper.",
            "estimated":"Estimated",
            "calculating":"Calculating…",
            "reached":"Reached",
            "profiles":"Profiles",
            "profilesSubtitle":"Choose a usage profile or let BUS detect your current workload automatically.",
            "usageProfile":"Usage profile",
            "activeProfile":"Active profile",
            "detectedProfile":"Automatically detected",
            "automaticallyDetected":"Automatically detected",
            "manuallySelected":"Manually selected",
            "expectedRuntime":"Expected runtime",
            "profileEfficiency":"profile efficiency",
            "profileReference":"Profile reference",
            "powerBalance":"Power balance",
            "powerBalanceSubtitle":"Draw positive · charging input negative",
            "energyDraw":"Energy draw",
            "energyInput":"Energy input",
            "profile.automatic.title":"Automatic",
            "profile.automatic.description":"BUS detects your current workload and blends it with learned profile times. During learning, the built-in model reference provides the comparison.",
            "profile.office.title":"Office",
            "profile.office.description":"Email, documents, spreadsheets, presentations and communication.",
            "profile.browser.title":"Browser",
            "profile.browser.description":"Web, communication, streaming and browser-based applications.",
            "profile.developer.title":"Developer",
            "profile.developer.description":"Xcode, IDEs, Terminal, Docker, compilers and simulators.",
            "profile.creative.title":"Creative",
            "profile.creative.description":"Image editing, design, photography and 3D applications.",
            "profile.video.title":"Video",
            "profile.video.description":"Video editing, rendering, encoding and media production.",
            "profile.gaming.title":"Gaming",
            "profile.gaming.description":"Games, 3D graphics and sustained CPU/GPU load.",
            "profile.audio.title":"Audio",
            "profile.audio.description":"Music production, DAWs, plugins and audio processing.",
            "profile.mixed.title":"Mixed",
            "profile.mixed.description":"Balanced use across several different workloads.",
            "currentInputPower":"Current input power",
            "adapterMaximum":"Adapter max.",
            "hardwareMeasured":"Measured by hardware sensor",
            "hardwarePartiallyMeasured":"Battery measured · input derived",
            "locallyEstimated":"Locally estimated",
            "hardwareHelper":"BUS Hardware Helper",
            "helperInstalled":"Hardware helper active",
            "helperMissing":"Hardware helper unavailable",

        ],
        .fr: [
            "overview":"Aperçu","overviewSubtitle":"Toutes les informations importantes en un coup d’œil.","history":"Historique","consumers":"Consommateurs","groupedProcessesInfo":"Les processus auxiliaires, de rendu et d’arrière-plan sont regroupés par application.","process":"processus","processes":"processus","settings":"Réglages","about":"À propos",
            "battery":"Batterie","power":"Puissance","duration":"Durée","status":"État","batteryMode":"Sur batterie","mainsMode":"Secteur",
            "score":"Score BUS","excellent":"Excellent","veryGood":"Très bon","good":"Bon","elevated":"Consommation élevée","high":"Forte consommation",
            "batteryHistory":"Historique de batterie","lastHours":"Session actuelle","topConsumers":"Principaux consommateurs","noData":"Pas encore de données",
            "openOverview":"Ouvrir l’aperçu","pause":"Pause","start":"Démarrer","quit":"Quitter BUS","reset":"Réinitialiser","export":"Exporter",
            "app":"App","share":"Part","estimatedBattery":"Batterie estimée","cpu":"CPU","disk":"E/S","wakeups":"Réveils",
            "groupByApp":"Par app",
            "groupByProcess":"Par processus",
            "showAll":"Tout afficher",
            "showActive":"Actifs uniquement",
            "showSignificant":"Au moins 1 %",
            "appProcess":"App / processus",
            "total":"Total",
            "mainProcess":"Processus principal",
            "historicalProcess":"Mesure précédente",
            "general":"Général","startAtLogin":"Lancer à la connexion","measurement":"Mesure","interval":"Intervalle",
            "autoReset":"Réinitialiser après la charge","autoResetAtFull":"Réinitialiser seulement à 100 %","language":"Langue","privacy":"Confidentialité",
            "privacyTitle":"100 % local","privacyText":"BUS ne transmet aucune mesure, donnée d’utilisation ou télémétrie. L’application fonctionne entièrement hors ligne.",
            "deleteData":"Supprimer toutes les données locales","confirmDelete":"Supprimer vraiment toutes les données locales ?","cancel":"Annuler","delete":"Supprimer",
            "welcome":"Bienvenue dans BUS","chooseLanguage":"Choisissez votre langue","continue":"Continuer","offlineBadge":"Aucune transmission",
            "credit":"BUS – Battery Usage Score par Heiko Große & ChatGPT © 2026","version":"Version",
            "estimateInfo":"Les parts par app sont des estimations basées sur la décharge, le CPU, les E/S et les réveils.",
            "charging":"En charge","remaining":"Niveau de batterie","updated":"Mis à jour","scoreExplanation":"Plus le score BUS est élevé, plus votre Mac est efficace sur batterie.",
            "scoreDetails":"Détail du score",
            "currentProjection":"Autonomie totale actuelle",
            "manufacturerReference":"Référence constructeur",
            "personalMedian":"Médiane personnelle",
            "modelScore":"Efficacité du modèle",
            "personalScore":"Efficacité personnelle",
            "personalRuntime":"Autonomie personnelle",
            "remainingEstimate":"Autonomie restante estimée",
            "thirtyDayAverage":"Moyenne sur 30 jours",
            "qualifiedSessions":"Sessions retenues",
            "runtimeStatisticsInfo":"Seules les sessions d’au moins 10 minutes et 3 % de décharge sont prises en compte.",
            "batterySessions":"Sessions batterie locales",
            "noRuntimeSessions":"Aucune session suffisamment longue enregistrée.",
            "deviceReference":"Référence de l’appareil",
            "detectedModel":"Modèle détecté",
            "automaticReference":"Référence automatique",
            "manualReference":"Référence manuelle",
            "automatic":"Automatique",
            "notAvailable":"Indisponible",
            "referenceInfo":"BUS utilise une référence locale du modèle. Une durée constructeur peut être saisie pour les modèles inconnus.",
            "scorePaused":"En pause",
            "scorePausedExplanation":"Le score BUS n’est pas évalué sur secteur.",
            "scoreCollecting":"Calcul en cours",
            "scoreCollectingExplanation":"BUS collecte au moins trois minutes de données avant le calcul.",
            "scoreReferenceMissing":"Référence absente",
            "scoreReferenceMissingExplanation":"Aucune référence constructeur ou personnelle n’est encore disponible.",
            "scoreRuntimeComparison":"Actuellement %.1f heures contre %.1f heures de référence.",
            "searchApps":"Rechercher apps et processus",
            "sortByColumn":"Trier selon cette colonne",
            "chargingActive":"Batterie en charge",
            "fullyCharged":"Charge complète",
            "chargeHolding":"Niveau de charge maintenu",
            "adapterPower":"Puissance de l’adaptateur",
            "systemConsumption":"Consommation du système",
            "batteryChargingPower":"Puissance de charge",
            "timeTo80":"Temps jusqu’à 80 %",
            "timeToFull":"Temps jusqu’à 100 %",
            "runtimeCurrentCharge":"Autonomie au niveau actuel",
            "runtimeFullCharge":"Autonomie à pleine charge",
            "chargeSpeed":"Vitesse de charge",
            "chargingEstimateInfo":"Les durées et flux sont des estimations locales lissées. Au-delà de 80 %, BUS tient compte de la réduction de puissance.",
            "estimated":"Estimé",
            "calculating":"Calcul en cours…",
            "reached":"Atteint",
            "profiles":"Profils",
            "usageProfile":"Profil d’utilisation",
            "activeProfile":"Profil actif",
            "detectedProfile":"Détecté automatiquement",
            "automaticallyDetected":"Détecté automatiquement",
            "manuallySelected":"Sélectionné manuellement",
            "expectedRuntime":"Autonomie attendue",
            "profileEfficiency":"efficacité du profil",
            "profileReference":"Référence du profil",
            "powerBalance":"Bilan de puissance",
            "powerBalanceSubtitle":"Décharge positive · charge négative",
            "energyDraw":"Énergie consommée",
            "energyInput":"Énergie ajoutée",
            "profile.automatic.title":"Automatic",
            "profile.office.title":"Office",
            "profile.browser.title":"Browser",
            "profile.developer.title":"Developer",
            "profile.creative.title":"Creative",
            "profile.video.title":"Video",
            "profile.gaming.title":"Gaming",
            "profile.audio.title":"Audio",
            "profile.mixed.title":"Mixed",
            "profilesSubtitle":"Choose a usage profile or let BUS detect your current workload automatically.",
            "currentInputPower":"Puissance d’entrée actuelle",
            "adapterMaximum":"Adaptateur max.",
            "hardwareMeasured":"Hardware measured",
            "hardwarePartiallyMeasured":"Battery measured · input derived",
            "locallyEstimated":"Locally estimated",
            "hardwareHelper":"BUS Hardware Helper",
            "helperInstalled":"Hardware helper active",
            "helperMissing":"Hardware helper unavailable",

        ],
        .es: [
            "overview":"Resumen","overviewSubtitle":"Toda la información importante de un vistazo.","history":"Historial","consumers":"Consumo","groupedProcessesInfo":"Los procesos auxiliares, de renderizado y en segundo plano se agrupan por aplicación.","process":"proceso","processes":"procesos","settings":"Ajustes","about":"Acerca de BUS",
            "battery":"Batería","power":"Potencia","duration":"Medición","status":"Estado","batteryMode":"Con batería","mainsMode":"Adaptador",
            "score":"Puntuación BUS","excellent":"Excelente","veryGood":"Muy bueno","good":"Bueno","elevated":"Consumo elevado","high":"Consumo alto",
            "batteryHistory":"Historial de batería","lastHours":"Sesión actual","topConsumers":"Principales consumidores","noData":"Aún no hay datos",
            "openOverview":"Abrir resumen","pause":"Pausa","start":"Iniciar","quit":"Salir de BUS","reset":"Restablecer","export":"Exportar",
            "app":"App","share":"Parte","estimatedBattery":"Batería estimada","cpu":"CPU","disk":"E/S","wakeups":"Activaciones",
            "groupByApp":"Por app",
            "groupByProcess":"Por proceso",
            "showAll":"Mostrar todo",
            "showActive":"Solo activos",
            "showSignificant":"Al menos 1 %",
            "appProcess":"App / proceso",
            "total":"Total",
            "mainProcess":"Proceso principal",
            "historicalProcess":"Medición anterior",
            "general":"General","startAtLogin":"Iniciar al acceder","measurement":"Medición","interval":"Intervalo",
            "autoReset":"Restablecer tras cargar","autoResetAtFull":"Restablecer solo al 100 %","language":"Idioma","privacy":"Privacidad",
            "privacyTitle":"100 % local","privacyText":"BUS no transmite mediciones, datos de uso ni telemetría. Funciona completamente sin conexión.",
            "deleteData":"Eliminar todos los datos locales","confirmDelete":"¿Eliminar todos los datos locales?","cancel":"Cancelar","delete":"Eliminar",
            "welcome":"Bienvenido a BUS","chooseLanguage":"Elige tu idioma","continue":"Continuar","offlineBadge":"Sin transmisión de datos",
            "credit":"BUS – Battery Usage Score por Heiko Große & ChatGPT © 2026","version":"Version",
            "estimateInfo":"Los valores por app son estimaciones basadas en descarga, CPU, E/S y activaciones.",
            "charging":"Cargando","remaining":"Nivel de batería","updated":"Actualizado","scoreExplanation":"Cuanto mayor sea la puntuación BUS, más eficiente funciona tu Mac con batería.",
            "scoreDetails":"Desglose de puntuación",
            "currentProjection":"Autonomía total actual",
            "manufacturerReference":"Referencia del fabricante",
            "personalMedian":"Mediana personal",
            "modelScore":"Eficiencia del modelo",
            "personalScore":"Eficiencia personal",
            "personalRuntime":"Autonomía personal",
            "remainingEstimate":"Tiempo restante estimado",
            "thirtyDayAverage":"Media de 30 días",
            "qualifiedSessions":"Sesiones válidas",
            "runtimeStatisticsInfo":"Solo se incluyen sesiones de al menos 10 minutos y 3 % de descarga.",
            "batterySessions":"Sesiones locales de batería",
            "noRuntimeSessions":"Aún no hay una sesión suficientemente larga.",
            "deviceReference":"Referencia del dispositivo",
            "detectedModel":"Modelo detectado",
            "automaticReference":"Referencia automática",
            "manualReference":"Referencia manual",
            "automatic":"Automático",
            "notAvailable":"No disponible",
            "referenceInfo":"BUS usa una referencia local del modelo. Para modelos desconocidos puede indicarse la autonomía del fabricante.",
            "scorePaused":"Pausado",
            "scorePausedExplanation":"La puntuación BUS no se evalúa con el adaptador conectado.",
            "scoreCollecting":"Calculando",
            "scoreCollectingExplanation":"BUS recopila al menos tres minutos antes de calcular.",
            "scoreReferenceMissing":"Falta referencia",
            "scoreReferenceMissingExplanation":"Aún no existe referencia del fabricante ni personal.",
            "scoreRuntimeComparison":"Actualmente %.1f horas frente a %.1f horas de referencia.",
            "searchApps":"Buscar apps y procesos",
            "sortByColumn":"Ordenar por esta columna",
            "chargingActive":"La batería se está cargando",
            "fullyCharged":"Carga completa",
            "chargeHolding":"Manteniendo el nivel de carga",
            "adapterPower":"Potencia del adaptador",
            "systemConsumption":"Consumo del sistema",
            "batteryChargingPower":"Potencia de carga de batería",
            "timeTo80":"Tiempo hasta 80 %",
            "timeToFull":"Tiempo hasta 100 %",
            "runtimeCurrentCharge":"Autonomía con la carga actual",
            "runtimeFullCharge":"Autonomía con carga completa",
            "chargeSpeed":"Velocidad de carga",
            "chargingEstimateInfo":"Los tiempos y flujos son estimaciones locales suavizadas. Por encima del 80 %, BUS tiene en cuenta la reducción de potencia.",
            "estimated":"Estimado",
            "calculating":"Calculando…",
            "reached":"Alcanzado",
            "profiles":"Perfiles",
            "usageProfile":"Perfil de uso",
            "activeProfile":"Perfil activo",
            "detectedProfile":"Detectado automáticamente",
            "automaticallyDetected":"Detectado automáticamente",
            "manuallySelected":"Seleccionado manualmente",
            "expectedRuntime":"Autonomía esperada",
            "profileEfficiency":"eficiencia del perfil",
            "profileReference":"Referencia del perfil",
            "powerBalance":"Balance de potencia",
            "powerBalanceSubtitle":"Consumo positivo · carga negativa",
            "energyDraw":"Consumo de energía",
            "energyInput":"Entrada de energía",
            "profile.automatic.title":"Automatic",
            "profile.office.title":"Office",
            "profile.browser.title":"Browser",
            "profile.developer.title":"Developer",
            "profile.creative.title":"Creative",
            "profile.video.title":"Video",
            "profile.gaming.title":"Gaming",
            "profile.audio.title":"Audio",
            "profile.mixed.title":"Mixed",
            "profilesSubtitle":"Choose a usage profile or let BUS detect your current workload automatically.",
            "currentInputPower":"Potencia de entrada actual",
            "adapterMaximum":"Adaptador máx.",
            "hardwareMeasured":"Hardware measured",
            "hardwarePartiallyMeasured":"Battery measured · input derived",
            "locallyEstimated":"Locally estimated",
            "hardwareHelper":"BUS Hardware Helper",
            "helperInstalled":"Hardware helper active",
            "helperMissing":"Hardware helper unavailable",

        ],
        .it: [
            "overview":"Panoramica","overviewSubtitle":"Tutte le informazioni importanti a colpo d’occhio.","history":"Cronologia","consumers":"Consumi","groupedProcessesInfo":"I processi helper, renderer e in background vengono raggruppati per app.","process":"processo","processes":"processi","settings":"Impostazioni","about":"Informazioni",
            "battery":"Batteria","power":"Potenza","duration":"Misurazione","status":"Stato","batteryMode":"A batteria","mainsMode":"Alimentatore",
            "score":"Punteggio BUS","excellent":"Eccellente","veryGood":"Molto buono","good":"Buono","elevated":"Consumo elevato","high":"Consumo alto",
            "batteryHistory":"Andamento batteria","lastHours":"Sessione attuale","topConsumers":"Principali consumatori","noData":"Nessun dato disponibile",
            "openOverview":"Apri panoramica","pause":"Pausa","start":"Avvia","quit":"Esci da BUS","reset":"Reimposta","export":"Esporta",
            "app":"App","share":"Quota","estimatedBattery":"Batteria stimata","cpu":"CPU","disk":"I/O","wakeups":"Risvegli",
            "groupByApp":"Per app",
            "groupByProcess":"Per processo",
            "showAll":"Mostra tutto",
            "showActive":"Solo attivi",
            "showSignificant":"Almeno 1%",
            "appProcess":"App / processo",
            "total":"Totale",
            "mainProcess":"Processo principale",
            "historicalProcess":"Misurazione precedente",
            "general":"Generale","startAtLogin":"Avvia al login","measurement":"Misurazione","interval":"Intervallo",
            "autoReset":"Reimposta dopo la ricarica","autoResetAtFull":"Reimposta solo al 100 %","language":"Lingua","privacy":"Privacy",
            "privacyTitle":"100% locale","privacyText":"BUS non trasmette misurazioni, dati d’uso o telemetria. Funziona completamente offline.",
            "deleteData":"Elimina tutti i dati locali","confirmDelete":"Eliminare tutti i dati locali?","cancel":"Annulla","delete":"Elimina",
            "welcome":"Benvenuto in BUS","chooseLanguage":"Scegli la lingua","continue":"Continua","offlineBadge":"Nessuna trasmissione dati",
            "credit":"BUS – Battery Usage Score di Heiko Große & ChatGPT © 2026","version":"Version",
            "estimateInfo":"Le quote per app sono stime basate su scarica, CPU, I/O e risvegli.",
            "charging":"In carica","remaining":"Livello batteria","updated":"Aggiornato","scoreExplanation":"Più alto è il punteggio BUS, più efficiente è il Mac a batteria.",
            "scoreDetails":"Dettaglio punteggio",
            "currentProjection":"Autonomia totale attuale",
            "manufacturerReference":"Riferimento produttore",
            "personalMedian":"Mediana personale",
            "modelScore":"Efficienza modello",
            "personalScore":"Efficienza personale",
            "personalRuntime":"Autonomia personale",
            "remainingEstimate":"Autonomia residua stimata",
            "thirtyDayAverage":"Media 30 giorni",
            "qualifiedSessions":"Sessioni valide",
            "runtimeStatisticsInfo":"Sono incluse solo sessioni di almeno 10 minuti e 3% di scarica.",
            "batterySessions":"Sessioni batteria locali",
            "noRuntimeSessions":"Nessuna sessione abbastanza lunga salvata.",
            "deviceReference":"Riferimento dispositivo",
            "detectedModel":"Modello rilevato",
            "automaticReference":"Riferimento automatico",
            "manualReference":"Riferimento manuale",
            "automatic":"Automatico",
            "notAvailable":"Non disponibile",
            "referenceInfo":"BUS usa un riferimento locale del modello. Per modelli sconosciuti è possibile inserire l’autonomia del produttore.",
            "scorePaused":"In pausa",
            "scorePausedExplanation":"Il punteggio BUS non viene valutato con alimentazione collegata.",
            "scoreCollecting":"Calcolo in corso",
            "scoreCollectingExplanation":"BUS raccoglie almeno tre minuti di dati prima della valutazione.",
            "scoreReferenceMissing":"Riferimento assente",
            "scoreReferenceMissingExplanation":"Non è ancora disponibile un riferimento del produttore o personale.",
            "scoreRuntimeComparison":"Attualmente %.1f ore rispetto a %.1f ore di riferimento.",
            "searchApps":"Cerca app e processi",
            "sortByColumn":"Ordina per questa colonna",
            "chargingActive":"Batteria in carica",
            "fullyCharged":"Carica completa",
            "chargeHolding":"Livello di carica mantenuto",
            "adapterPower":"Potenza alimentatore",
            "systemConsumption":"Consumo del sistema",
            "batteryChargingPower":"Potenza di ricarica",
            "timeTo80":"Tempo fino all’80%",
            "timeToFull":"Tempo fino al 100%",
            "runtimeCurrentCharge":"Autonomia alla carica attuale",
            "runtimeFullCharge":"Autonomia a piena carica",
            "chargeSpeed":"Velocità di ricarica",
            "chargingEstimateInfo":"Tempi e flussi sono stime locali mediate. Oltre l’80%, BUS considera la riduzione della potenza.",
            "estimated":"Stimato",
            "calculating":"Calcolo…",
            "reached":"Raggiunto",
            "profiles":"Profili",
            "usageProfile":"Profilo di utilizzo",
            "activeProfile":"Profilo attivo",
            "detectedProfile":"Rilevato automaticamente",
            "automaticallyDetected":"Rilevato automaticamente",
            "manuallySelected":"Selezionato manualmente",
            "expectedRuntime":"Autonomia prevista",
            "profileEfficiency":"efficienza profilo",
            "profileReference":"Riferimento profilo",
            "powerBalance":"Bilancio di potenza",
            "powerBalanceSubtitle":"Consumo positivo · carica negativa",
            "energyDraw":"Energia consumata",
            "energyInput":"Energia immessa",
            "profile.automatic.title":"Automatic",
            "profile.office.title":"Office",
            "profile.browser.title":"Browser",
            "profile.developer.title":"Developer",
            "profile.creative.title":"Creative",
            "profile.video.title":"Video",
            "profile.gaming.title":"Gaming",
            "profile.audio.title":"Audio",
            "profile.mixed.title":"Mixed",
            "profilesSubtitle":"Choose a usage profile or let BUS detect your current workload automatically.",
            "currentInputPower":"Potenza in ingresso attuale",
            "adapterMaximum":"Alimentatore max.",
            "hardwareMeasured":"Hardware measured",
            "hardwarePartiallyMeasured":"Battery measured · input derived",
            "locallyEstimated":"Locally estimated",
            "hardwareHelper":"BUS Hardware Helper",
            "helperInstalled":"Hardware helper active",
            "helperMissing":"Hardware helper unavailable",

        ],
        .nl: [
            "overview":"Overzicht","overviewSubtitle":"Alle belangrijke informatie in één oogopslag.","history":"Geschiedenis","consumers":"Verbruikers","groupedProcessesInfo":"Bijbehorende hulp-, renderer- en achtergrondprocessen worden per app gegroepeerd.","process":"proces","processes":"processen","settings":"Instellingen","about":"Over BUS",
            "battery":"Batterij","power":"Vermogen","duration":"Meting","status":"Status","batteryMode":"Op batterij","mainsMode":"Netstroom",
            "score":"BUS-score","excellent":"Uitstekend","veryGood":"Zeer goed","good":"Goed","elevated":"Verhoogd verbruik","high":"Hoog verbruik",
            "batteryHistory":"Batterijverloop","lastHours":"Huidige meting","topConsumers":"Grootste verbruikers","noData":"Nog geen gegevens",
            "openOverview":"Open overzicht","pause":"Pauze","start":"Start","quit":"Stop BUS","reset":"Reset","export":"Exporteer",
            "app":"App","share":"Aandeel","estimatedBattery":"Geschatte batterij","cpu":"CPU","disk":"I/O","wakeups":"Wake-ups",
            "groupByApp":"Per app",
            "groupByProcess":"Per proces",
            "showAll":"Alles tonen",
            "showActive":"Alleen actief",
            "showSignificant":"Minimaal 1%",
            "appProcess":"App / proces",
            "total":"Totaal",
            "mainProcess":"Hoofdproces",
            "historicalProcess":"Eerdere meting",
            "general":"Algemeen","startAtLogin":"Start bij aanmelden","measurement":"Meting","interval":"Meetinterval",
            "autoReset":"Reset na opladen","autoResetAtFull":"Alleen bij 100 % resetten","language":"Taal","privacy":"Privacy",
            "privacyTitle":"100% lokaal","privacyText":"BUS verzendt geen metingen, gebruiksgegevens of telemetrie. De app werkt volledig offline.",
            "deleteData":"Alle lokale gegevens verwijderen","confirmDelete":"Alle lokale gegevens verwijderen?","cancel":"Annuleer","delete":"Verwijder",
            "welcome":"Welkom bij BUS","chooseLanguage":"Kies je taal","continue":"Doorgaan","offlineBadge":"Geen gegevensoverdracht",
            "credit":"BUS – Battery Usage Score door Heiko Große & ChatGPT © 2026","version":"Version",
            "estimateInfo":"Aandelen per app zijn schattingen op basis van ontlading, CPU, I/O en wake-ups.",
            "charging":"Opladen","remaining":"Batterijniveau","updated":"Bijgewerkt","scoreExplanation":"Hoe hoger de BUS-score, hoe efficiënter je Mac op batterij werkt.",
            "scoreDetails":"Score-opbouw",
            "currentProjection":"Huidige totale gebruiksduur",
            "manufacturerReference":"Fabrikantsreferentie",
            "personalMedian":"Persoonlijke mediaan",
            "modelScore":"Modelefficiëntie",
            "personalScore":"Persoonlijke efficiëntie",
            "personalRuntime":"Persoonlijke batterijduur",
            "remainingEstimate":"Geschatte resterende tijd",
            "thirtyDayAverage":"30-daags gemiddelde",
            "qualifiedSessions":"Geldige sessies",
            "runtimeStatisticsInfo":"Alleen sessies van minimaal 10 minuten en 3% ontlading tellen mee.",
            "batterySessions":"Lokale batterijsessies",
            "noRuntimeSessions":"Nog geen voldoende lange sessie opgeslagen.",
            "deviceReference":"Apparaatreferentie",
            "detectedModel":"Gedetecteerd model",
            "automaticReference":"Automatische referentie",
            "manualReference":"Handmatige referentie",
            "automatic":"Automatisch",
            "notAvailable":"Niet beschikbaar",
            "referenceInfo":"BUS gebruikt een lokaal modelprofiel. Voor onbekende modellen kan de fabrieksduur handmatig worden ingevuld.",
            "scorePaused":"Gepauzeerd",
            "scorePausedExplanation":"De BUS-score wordt niet beoordeeld op netstroom.",
            "scoreCollecting":"Wordt bepaald",
            "scoreCollectingExplanation":"BUS verzamelt minimaal drie minuten gegevens.",
            "scoreReferenceMissing":"Referentie ontbreekt",
            "scoreReferenceMissingExplanation":"Er is nog geen fabrikant- of persoonlijke referentie.",
            "scoreRuntimeComparison":"Momenteel %.1f uur tegenover %.1f referentie-uren.",
            "searchApps":"Apps en processen zoeken",
            "sortByColumn":"Sorteren op deze kolom",
            "chargingActive":"Batterij wordt opgeladen",
            "fullyCharged":"Volledig opgeladen",
            "chargeHolding":"Laadniveau wordt vastgehouden",
            "adapterPower":"Adaptervermogen",
            "systemConsumption":"Systeemverbruik",
            "batteryChargingPower":"Laadvermogen batterij",
            "timeTo80":"Tijd tot 80%",
            "timeToFull":"Tijd tot 100%",
            "runtimeCurrentCharge":"Gebruiksduur bij huidige lading",
            "runtimeFullCharge":"Gebruiksduur bij volle lading",
            "chargeSpeed":"Laadsnelheid",
            "chargingEstimateInfo":"Laadtijden en vermogensstromen zijn lokale, afgevlakte schattingen. Boven 80% houdt BUS rekening met afnemend laadvermogen.",
            "estimated":"Geschat",
            "calculating":"Wordt berekend…",
            "reached":"Bereikt",
            "profiles":"Profielen",
            "usageProfile":"Gebruiksprofiel",
            "activeProfile":"Actief profiel",
            "detectedProfile":"Automatisch gedetecteerd",
            "automaticallyDetected":"Automatisch gedetecteerd",
            "manuallySelected":"Handmatig geselecteerd",
            "expectedRuntime":"Verwachte gebruiksduur",
            "profileEfficiency":"profielefficiëntie",
            "profileReference":"Profielreferentie",
            "powerBalance":"Vermogensbalans",
            "powerBalanceSubtitle":"Verbruik positief · laden negatief",
            "energyDraw":"Energieverbruik",
            "energyInput":"Energietoevoer",
            "profile.automatic.title":"Automatic",
            "profile.office.title":"Office",
            "profile.browser.title":"Browser",
            "profile.developer.title":"Developer",
            "profile.creative.title":"Creative",
            "profile.video.title":"Video",
            "profile.gaming.title":"Gaming",
            "profile.audio.title":"Audio",
            "profile.mixed.title":"Mixed",
            "profilesSubtitle":"Choose a usage profile or let BUS detect your current workload automatically.",
            "currentInputPower":"Huidig ingangsvermogen",
            "adapterMaximum":"Adapter max.",
            "hardwareMeasured":"Hardware measured",
            "hardwarePartiallyMeasured":"Battery measured · input derived",
            "locallyEstimated":"Locally estimated",
            "hardwareHelper":"BUS Hardware Helper",
            "helperInstalled":"Hardware helper active",
            "helperMissing":"Hardware helper unavailable",

        ],
        .ja: [
            "overview":"概要","overviewSubtitle":"重要な情報をひと目で確認できます。","history":"履歴","consumers":"消費アプリ","groupedProcessesInfo":"関連するヘルパー、レンダラー、バックグラウンドプロセスをアプリごとにまとめます。","process":"プロセス","processes":"プロセス","settings":"設定","about":"BUSについて",
            "battery":"バッテリー","power":"電力","duration":"測定時間","status":"状態","batteryMode":"バッテリー駆動","mainsMode":"電源接続",
            "score":"BUSスコア","excellent":"非常に良い","veryGood":"とても良い","good":"良い","elevated":"消費量が高め","high":"消費量が高い",
            "batteryHistory":"バッテリー履歴","lastHours":"現在の測定","topConsumers":"上位の消費アプリ","noData":"まだデータがありません",
            "openOverview":"概要を開く","pause":"一時停止","start":"開始","quit":"BUSを終了","reset":"リセット","export":"書き出す",
            "app":"アプリ","share":"割合","estimatedBattery":"推定消費","cpu":"CPU","disk":"I/O","wakeups":"ウェイクアップ",
            "groupByApp":"アプリ別",
            "groupByProcess":"プロセス別",
            "showAll":"すべて表示",
            "showActive":"実行中のみ",
            "showSignificant":"1%以上",
            "appProcess":"アプリ / プロセス",
            "total":"合計",
            "mainProcess":"メインプロセス",
            "historicalProcess":"以前の測定",
            "general":"一般","startAtLogin":"ログイン時に起動","measurement":"測定","interval":"測定間隔",
            "autoReset":"充電終了後に自動リセット","autoResetAtFull":"100 % 到達時のみリセット","language":"言語","privacy":"プライバシー",
            "privacyTitle":"100% ローカル","privacyText":"BUSは測定値、利用状況、テレメトリを送信しません。完全にオフラインで動作します。",
            "deleteData":"ローカルデータをすべて削除","confirmDelete":"ローカルデータを削除しますか？","cancel":"キャンセル","delete":"削除",
            "welcome":"BUSへようこそ","chooseLanguage":"言語を選択","continue":"続ける","offlineBadge":"データ送信なし",
            "credit":"BUS – Battery Usage Score by Heiko Große & ChatGPT © 2026","version":"Version",
            "estimateInfo":"アプリ別の値は、放電量、CPU、I/O、ウェイクアップに基づく推定です。",
            "charging":"充電中","remaining":"バッテリー残量","updated":"更新","scoreExplanation":"BUSスコアが高いほど、バッテリー駆動時の効率が良好です。",
            "scoreDetails":"スコア内訳",
            "currentProjection":"現在の総稼働時間",
            "manufacturerReference":"メーカー基準",
            "personalMedian":"個人中央値",
            "modelScore":"モデル効率",
            "personalScore":"個人効率",
            "personalRuntime":"個人バッテリー時間",
            "remainingEstimate":"推定残り時間",
            "thirtyDayAverage":"30日平均",
            "qualifiedSessions":"有効セッション",
            "runtimeStatisticsInfo":"10分以上かつ3%以上消費したセッションのみ集計します。",
            "batterySessions":"ローカルバッテリーセッション",
            "noRuntimeSessions":"十分な長さのセッションはまだありません。",
            "deviceReference":"デバイス基準",
            "detectedModel":"検出モデル",
            "automaticReference":"自動基準",
            "manualReference":"手動基準",
            "automatic":"自動",
            "notAvailable":"未登録",
            "referenceInfo":"BUSはローカルのモデル基準を使用します。未知のモデルはメーカー公称時間を手動設定できます。",
            "scorePaused":"一時停止",
            "scorePausedExplanation":"電源接続中はBUSスコアを評価しません。",
            "scoreCollecting":"計測中",
            "scoreCollectingExplanation":"評価前に少なくとも3分間データを収集します。",
            "scoreReferenceMissing":"基準なし",
            "scoreReferenceMissingExplanation":"メーカーまたは個人基準がまだありません。",
            "scoreRuntimeComparison":"現在 %.1f 時間、基準 %.1f 時間です。",
            "searchApps":"アプリとプロセスを検索",
            "sortByColumn":"この列で並べ替え",
            "chargingActive":"バッテリーを充電中",
            "fullyCharged":"充電完了",
            "chargeHolding":"充電レベルを維持中",
            "adapterPower":"アダプター電力",
            "systemConsumption":"システム消費電力",
            "batteryChargingPower":"バッテリー充電電力",
            "timeTo80":"80%までの時間",
            "timeToFull":"100%までの時間",
            "runtimeCurrentCharge":"現在の充電量での稼働時間",
            "runtimeFullCharge":"満充電時の稼働時間",
            "chargeSpeed":"充電速度",
            "chargingEstimateInfo":"充電時間と電力フローはローカルで平滑化した推定値です。80%以降は充電電力の低下を考慮します。",
            "estimated":"推定",
            "calculating":"計算中…",
            "reached":"到達",
            "profiles":"プロファイル",
            "usageProfile":"使用プロファイル",
            "activeProfile":"現在のプロファイル",
            "detectedProfile":"自動検出",
            "automaticallyDetected":"自動検出",
            "manuallySelected":"手動選択",
            "expectedRuntime":"予想稼働時間",
            "profileEfficiency":"プロファイル効率",
            "profileReference":"プロファイル基準",
            "powerBalance":"電力収支",
            "powerBalanceSubtitle":"消費は正 · 充電は負",
            "energyDraw":"電力消費",
            "energyInput":"電力供給",
            "profile.automatic.title":"Automatic",
            "profile.office.title":"Office",
            "profile.browser.title":"Browser",
            "profile.developer.title":"Developer",
            "profile.creative.title":"Creative",
            "profile.video.title":"Video",
            "profile.gaming.title":"Gaming",
            "profile.audio.title":"Audio",
            "profile.mixed.title":"Mixed",
            "profilesSubtitle":"Choose a usage profile or let BUS detect your current workload automatically.",
            "currentInputPower":"現在の入力電力",
            "adapterMaximum":"アダプター最大",
            "hardwareMeasured":"Hardware measured",
            "hardwarePartiallyMeasured":"Battery measured · input derived",
            "locallyEstimated":"Locally estimated",
            "hardwareHelper":"BUS Hardware Helper",
            "helperInstalled":"Hardware helper active",
            "helperMissing":"Hardware helper unavailable",

        ],
        .zhHans: [
            "overview":"概览","overviewSubtitle":"所有重要信息一目了然。","history":"历史","consumers":"耗电应用","groupedProcessesInfo":"相关的辅助、渲染和后台进程会按应用分组。","process":"进程","processes":"进程","settings":"设置","about":"关于 BUS",
            "battery":"电池","power":"功率","duration":"测量时间","status":"状态","batteryMode":"电池供电","mainsMode":"电源供电",
            "score":"BUS 评分","excellent":"优秀","veryGood":"很好","good":"良好","elevated":"耗电偏高","high":"高耗电",
            "batteryHistory":"电池历史","lastHours":"当前测量周期","topConsumers":"主要耗电应用","noData":"暂无可用数据",
            "openOverview":"打开概览","pause":"暂停","start":"开始","quit":"退出 BUS","reset":"重置","export":"导出",
            "app":"应用","share":"占比","estimatedBattery":"估算电量","cpu":"CPU","disk":"I/O","wakeups":"唤醒次数",
            "groupByApp":"按应用",
            "groupByProcess":"按进程",
            "showAll":"显示全部",
            "showActive":"仅活动",
            "showSignificant":"至少 1%",
            "appProcess":"应用 / 进程",
            "total":"总计",
            "mainProcess":"主进程",
            "historicalProcess":"以前的测量",
            "general":"通用","startAtLogin":"登录时启动","measurement":"测量","interval":"采样间隔",
            "autoReset":"充电结束后自动重置","autoResetAtFull":"仅在 100 % 时重置","language":"语言","privacy":"隐私",
            "privacyTitle":"100% 本地","privacyText":"BUS 不会传输测量值、使用数据或遥测信息。应用完全离线运行。",
            "deleteData":"删除所有本地数据","confirmDelete":"确定删除所有本地数据？","cancel":"取消","delete":"删除",
            "welcome":"欢迎使用 BUS","chooseLanguage":"选择语言","continue":"继续","offlineBadge":"不传输数据",
            "credit":"BUS – Battery Usage Score，由 Heiko Große & ChatGPT 于 2026 年创作","version":"Version",
            "estimateInfo":"每个应用的占比根据放电量、CPU、磁盘 I/O 和唤醒次数估算。",
            "charging":"充电中","remaining":"电池电量","updated":"已更新","scoreExplanation":"BUS 评分越高，Mac 在电池模式下运行越高效。",
            "scoreDetails":"评分明细",
            "currentProjection":"当前总续航",
            "manufacturerReference":"厂商参考",
            "personalMedian":"个人中位数",
            "modelScore":"机型效率",
            "personalScore":"个人效率",
            "personalRuntime":"个人续航",
            "remainingEstimate":"预计剩余时间",
            "thirtyDayAverage":"30天平均",
            "qualifiedSessions":"有效会话",
            "runtimeStatisticsInfo":"仅统计至少10分钟且耗电不少于3%的电池会话。",
            "batterySessions":"本地电池会话",
            "noRuntimeSessions":"尚无足够长的电池会话。",
            "deviceReference":"设备参考",
            "detectedModel":"检测到的机型",
            "automaticReference":"自动参考",
            "manualReference":"手动参考",
            "automatic":"自动",
            "notAvailable":"未收录",
            "referenceInfo":"BUS使用本地机型参考。未知机型可手动填写厂商续航。",
            "scorePaused":"已暂停",
            "scorePausedExplanation":"接通电源时不计算BUS评分。",
            "scoreCollecting":"正在计算",
            "scoreCollectingExplanation":"BUS至少收集三分钟数据后再评分。",
            "scoreReferenceMissing":"缺少参考",
            "scoreReferenceMissingExplanation":"尚无厂商或个人参考。",
            "scoreRuntimeComparison":"当前 %.1f 小时，参考 %.1f 小时。",
            "searchApps":"搜索应用和进程",
            "sortByColumn":"按此列排序",
            "chargingActive":"电池正在充电",
            "fullyCharged":"已充满",
            "chargeHolding":"正在保持电量",
            "adapterPower":"电源适配器功率",
            "systemConsumption":"系统功耗",
            "batteryChargingPower":"电池充电功率",
            "timeTo80":"充至80%的时间",
            "timeToFull":"充至100%的时间",
            "runtimeCurrentCharge":"当前电量预计续航",
            "runtimeFullCharge":"满电预计续航",
            "chargeSpeed":"充电速度",
            "chargingEstimateInfo":"充电时间和功率流为本地平滑估算值。超过80%后，BUS会考虑充电功率下降。",
            "estimated":"估算",
            "calculating":"正在计算…",
            "reached":"已达到",
            "profiles":"配置文件",
            "usageProfile":"使用配置",
            "activeProfile":"当前配置",
            "detectedProfile":"自动检测",
            "automaticallyDetected":"自动检测",
            "manuallySelected":"手动选择",
            "expectedRuntime":"预计续航",
            "profileEfficiency":"配置效率",
            "profileReference":"配置参考",
            "powerBalance":"功率平衡",
            "powerBalanceSubtitle":"耗电为正 · 充电为负",
            "energyDraw":"能量消耗",
            "energyInput":"能量输入",
            "profile.automatic.title":"Automatic",
            "profile.office.title":"Office",
            "profile.browser.title":"Browser",
            "profile.developer.title":"Developer",
            "profile.creative.title":"Creative",
            "profile.video.title":"Video",
            "profile.gaming.title":"Gaming",
            "profile.audio.title":"Audio",
            "profile.mixed.title":"Mixed",
            "profilesSubtitle":"Choose a usage profile or let BUS detect your current workload automatically.",
            "currentInputPower":"当前输入功率",
            "adapterMaximum":"适配器最大",
            "hardwareMeasured":"Hardware measured",
            "hardwarePartiallyMeasured":"Battery measured · input derived",
            "locallyEstimated":"Locally estimated",
            "hardwareHelper":"BUS Hardware Helper",
            "helperInstalled":"Hardware helper active",
            "helperMissing":"Hardware helper unavailable",

        ]
    ]
}

extension View {
    func localizedEnvironment(_ localizer: Localizer) -> some View {
        environment(\.locale, Locale(identifier: localizer.language.rawValue))
    }
}
